0-custom_http_response_header

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,84 +1,23 @@
 #!/usr/bin/env bash
-# duplicate web-01 to web-02
-# these scripts are an upgrade from the web-server scripts...
+# Script to configure Nginx with a custom HTTP response header X-Served-By
 
-# uncomment to see the script run in action
-#set -x
+set -e  # Exit immediately if a command exits with a non-zero status
 
-echo -e "Updating and doing some minor checks...\n"
+# Update packages and install Nginx
+sudo apt-get update -y
+sudo apt-get install -y nginx
 
-function install() {
-	command -v "$1" &> /dev/null
+# Ensure Nginx is running without systemctl
+sudo service nginx start || sudo /etc/init.d/nginx start
 
-	#shellcheck disable=SC2181
-	if [ $? -ne 0 ]; then
-		echo -e "	Installing: $1$\n"
-		sudo apt-get update -y -qq && \
-			sudo apt-get install -y "$1" -qq
-		echo -e "\n"
-	else
-		echo -e "	${1} is already installed.\n"
-	fi
-}
+# Get the current hostname
+HOSTNAME=$(hostname)
 
-install nginx #install nginx
+# Configure Nginx to include custom header
+sudo sed -i "/server_name _;/a \\n    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
 
-echo -e "\nSetting up some minor stuff.\n"
+# Restart Nginx without systemctl
+sudo service nginx restart || { sudo killall -q nginx && sudo nginx; }
 
-# allowing nginx on firewall
-sudo ufw allow 'Nginx HTTP'
+echo "1"
 
-# Give the user ownership to website files for easy editing
-if [ -d "/var/www" ]; then
-	sudo chown -R "$USER":"$USER" /var/www
-	sudo chmod -R 755 /var/www
-else
-	sudo mkdir -p /var/www
-	sudo chown -R "$USER":"$USER" /var/www
-	sudo chmod -R 755 /var/www
-fi
-
-# create directories if not present
-for dir in /var/www/{html,error}; do
-	if ! [ -d "$dir" ]; then
-		mkdir -p "$dir"
-	fi
-done
-
-# creating new index
-echo "Hello World!" > /var/www/html/index.html
-
-# create new error page
-echo "Ceci n'est pas une page" > /var/www/html/error_404.html
-
-# backup default server config file
-sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
-
-server_config=\
-"server {
-		listen 80 default_server;
-		listen [::]:80 default_server;
-		root /var/www/html;
-		index index.html index.htm index.nginx-debian.html
-		server_name_;
-		add_header X-Served-By \$hostname;
-		location / {
-			try_files \$uri \$uri/ =404;
-		}
-		if (\$request_filename ~ redirect_me){
-			rewrite ^ https://th3-gr00t.tk/ permanent;
-		}
-		error_page 404 /error_404.html;
-		location = /error_404.html {
-			internal;
-		}
-}"
-
-#shellcheck disable=SC2154
-echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
-
-if [ "$(pgrep -c nginx)" -le 0 ]; then
-	sudo service nginx start
-else
-	sudo service nginx restart
-fi
